### ISSUE TITLE
DeSci Coin Giveaway

### ISSUE THREAD

**Issue by makeasnek** [TheSCInitiative/Gridcoin#2]

**Comment by jring-o** [comment]
- [x] Poll Gridcoin community -- can we use coins to giveaway
- [x] Approach other DeSci coins
   - [x] Banano
   ~- [ ] Obyte~
   - [x] Curecoin
   - [x] Etica
   - [x] Others
- [x] Write reddit post 
- [x] Send info to r/CC mods
- [x] Send GRC to Delta

**Comment by delta1513** [comment]
@jamescowens To fund the coin giveaway for Gridcoin.

**Comment by jring-o** [comment]
January 11th-14th = social media posts.
January 14th = event.

Set up streaming infrastructure.
